name: Pull Request Template
title: "Your PR Title Here (@your_github_username)"
body:
  - type: markdown
    value: "### Description\n\nPlease describe the change(s) made in your PR."

  - type: textarea
    id: "description"
    attributes:
      label: "Description"
      description: "Provide a brief summary of the changes made in this pull request."
      placeholder: "Add your description here..."
  - type: textarea
    attributes:
      label: "Mentions"
      description: "mention an issue, PR, or discussion on GitHub by referencing its hash number, e.g., [#1234](https://github.com/piyushgarg-dev/leetcode-whisper-chrome-extension/pull/1234)."
      placeholder: "closes #1234"

  - type: checkboxes
    id: "checks"
    attributes:
      label: "Checklist"
      options:
        - label: "Mention an issue, PR, or discussion on GitHub by referencing its hash number, e.g., [#1234]."
        - label: "Check if any open issues are related to this PR and tag them below."
        - label: "Ensure the PR title follows the Conventional Commits standard. (<https://www.conventionalcommits.org> for more info)."
        - label: "Include your GitHub username prefixed with @ inside parentheses at the end of the PR title."
  - type: markdown
    value: "I know these tasks seem boring, but they help us and will help you too!"
